// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrHWbtXKLn_PeO189RyI48qRWMvyvuaUQ',
    appId: '1:513895911773:web:d5c21dcbe00f46ca6298b4',
    messagingSenderId: '513895911773',
    projectId: 'foodlette-3bdf2',
    authDomain: 'foodlette-3bdf2.firebaseapp.com',
    databaseURL: 'https://foodlette-3bdf2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodlette-3bdf2.firebasestorage.app',
    measurementId: 'G-YGMH0E6982',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVUqukV_76VCAQTgFUHnx6eKsjxqMOoKk',
    appId: '1:513895911773:android:f977eb7c1e4877486298b4',
    messagingSenderId: '513895911773',
    projectId: 'foodlette-3bdf2',
    databaseURL: 'https://foodlette-3bdf2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodlette-3bdf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOc9uqYbFmh06fVg30FJV_vU_ePyC40rw',
    appId: '1:513895911773:ios:0332c43f80d1217a6298b4',
    messagingSenderId: '513895911773',
    projectId: 'foodlette-3bdf2',
    databaseURL: 'https://foodlette-3bdf2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodlette-3bdf2.firebasestorage.app',
    iosClientId: '513895911773-mdkv9gh6anas45mek7ngtdl5r5akoqqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodlettemobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOc9uqYbFmh06fVg30FJV_vU_ePyC40rw',
    appId: '1:513895911773:ios:0332c43f80d1217a6298b4',
    messagingSenderId: '513895911773',
    projectId: 'foodlette-3bdf2',
    databaseURL: 'https://foodlette-3bdf2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodlette-3bdf2.firebasestorage.app',
    iosClientId: '513895911773-mdkv9gh6anas45mek7ngtdl5r5akoqqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodlettemobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrHWbtXKLn_PeO189RyI48qRWMvyvuaUQ',
    appId: '1:513895911773:web:f801688a86cb0fe36298b4',
    messagingSenderId: '513895911773',
    projectId: 'foodlette-3bdf2',
    authDomain: 'foodlette-3bdf2.firebaseapp.com',
    databaseURL: 'https://foodlette-3bdf2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodlette-3bdf2.firebasestorage.app',
    measurementId: 'G-LW894G1P9E',
  );

}